### ISSUE TITLE
Cannot build license list

### ISSUE THREAD

**Issue by utkarshshendge** [Ugtan/spdx-license-match-tool#15]
While trying to build licence list I am getting this:
I used `python matcher.py -f <file-name> `

```
Building SPDX License List. This may take a while...
Traceback (most recent call last):
  File "matcher.py", line 59, in <module>
    matcher()
  File "C:\Users\utka\venv\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\utka\venv\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "C:\Users\utka\venv\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\utka\venv\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "matcher.py", line 32, in matcher
    build_spdx_licenses()
  File "C:\Users\utka\Desktop\gsoc5\spdx-license-matcher\spdx_license_matcher\build_licenses.py", line 38, in build_spdx_licenses
    responses = list(pool.map(get_url, licensesUrl))
  File "c:\users\utka\appdata\local\programs\python\python37\lib\concurrent\futures\_base.py", line 586, in result_iterator
    yield fs.pop().result()
  File "c:\users\utka\appdata\local\programs\python\python37\lib\concurrent\futures\_base.py", line 425, in result
    return self.__get_result()
  File "c:\users\utka\appdata\local\programs\python\python37\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
  File "c:\users\utka\appdata\local\programs\python\python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\utka\Desktop\gsoc5\spdx-license-matcher\spdx_license_matcher\build_licenses.py", line 20, in get_url
    res = requests.get(url, headers=headers)
  File "C:\Users\utka\venv\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\utka\venv\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\utka\venv\lib\site-packages\requests\sessions.py", line 516, in request
    prep = self.prepare_request(req)
  File "C:\Users\utka\venv\lib\site-packages\requests\sessions.py", line 459, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\utka\venv\lib\site-packages\requests\models.py", line 314, in prepare
    self.prepare_url(url, params)
  File "C:\Users\utka\venv\lib\site-packages\requests\models.py", line 388, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL './AFL-2.0.html': No schema supplied. Perhaps you meant http://./AFL-2.0.html?
```

**Comment by utkarshshendge** [comment]
Hi @rtgdk , it looks like the value of `"detailsUrl"` is changed in https://spdx.org/licenses/licenses.json.

**Comment by m1kit** [comment]
Hi @utkarshshendge, I'm working on this issue. (See https://github.com/spdx/spdx-license-matcher/pull/14 for details)

Please wait until https://github.com/spdx/Spdx-Java-Library/pull/47 is merged, or you can pull a fix from https://github.com/m1kit/spdx-license-matcher.

**Comment by utkarshshendge** [comment]
Got it !!  
Thanks @m1kit .
